// ============================================================================
// Nakshatra Constants
// ============================================================================

import type { Nakshatra } from '@/types/database'

export const NAKSHATRAS: Nakshatra[] = [
  'Ashwini',
  'Bharani',
  'Krittika',
  'Rohini',
  'Mrigashirsha',
  'Ardra',
  'Punarvasu',
  'Pushya',
  'Ashlesha',
  'Magha',
  'Purva Phalguni',
  'Uttara Phalguni',
  'Hasta',
  'Chitra',
  'Swati',
  'Vishakha',
  'Anuradha',
  'Jyeshta',
  'Moola',
  'Purva Ashadha',
  'Uttara Ashadha',
  'Shravana',
  'Dhanishta',
  'Shatabhisha',
  'Purva Bhadrapada',
  'Uttara Bhadrapada',
  'Revati',
]

export const NAKSHATRA_INFO: Record<Nakshatra, { deity: string; meaning: string }> = {
  'Ashwini': { deity: 'Ashwini Kumaras', meaning: 'Horse woman' },
  'Bharani': { deity: 'Yama', meaning: 'The bearer' },
  'Krittika': { deity: 'Agni', meaning: 'The cutter' },
  'Rohini': { deity: 'Brahma', meaning: 'The red one' },
  'Mrigashirsha': { deity: 'Soma', meaning: 'Deer\'s head' },
  'Ardra': { deity: 'Rudra', meaning: 'The moist one' },
  'Punarvasu': { deity: 'Aditi', meaning: 'Return of the light' },
  'Pushya': { deity: 'Brihaspati', meaning: 'Nourisher' },
  'Ashlesha': { deity: 'Nagas', meaning: 'The entwiner' },
  'Magha': { deity: 'Pitris', meaning: 'The mighty' },
  'Purva Phalguni': { deity: 'Bhaga', meaning: 'Former reddish one' },
  'Uttara Phalguni': { deity: 'Aryaman', meaning: 'Latter reddish one' },
  'Hasta': { deity: 'Savitar', meaning: 'The hand' },
  'Chitra': { deity: 'Vishwakarma', meaning: 'Bright' },
  'Swati': { deity: 'Vayu', meaning: 'Sword' },
  'Vishakha': { deity: 'Indra-Agni', meaning: 'Forked branch' },
  'Anuradha': { deity: 'Mitra', meaning: 'Following Radha' },
  'Jyeshta': { deity: 'Indra', meaning: 'The eldest' },
  'Moola': { deity: 'Nirriti', meaning: 'The root' },
  'Purva Ashadha': { deity: 'Apas', meaning: 'Former invincible one' },
  'Uttara Ashadha': { deity: 'Vishvadevas', meaning: 'Latter invincible one' },
  'Shravana': { deity: 'Vishnu', meaning: 'Hearing' },
  'Dhanishta': { deity: 'Vasus', meaning: 'The wealthiest' },
  'Shatabhisha': { deity: 'Varuna', meaning: 'Hundred physicians' },
  'Purva Bhadrapada': { deity: 'Aja Ekapada', meaning: 'Former blessed feet' },
  'Uttara Bhadrapada': { deity: 'Ahir Budhnya', meaning: 'Latter blessed feet' },
  'Revati': { deity: 'Pushan', meaning: 'Wealthy' },
}
