#!/usr/bin/env node
/**
 * Prints the live account / role / membership table for a Supabase project.
 *
 * docs/ACCESS-AND-ROLES.md documents the role MODEL, which changes rarely.
 * Who actually holds a role changes whenever someone is granted one, so that
 * list is not written down — it is read from the database by this script.
 *
 *   node scripts/list-access.mjs            # the project in .env.local
 *   node scripts/list-access.mjs --markdown # a table to paste into a doc
 *
 * Dependency-free: Node built-ins only. Needs SUPABASE_SERVICE_ROLE_KEY,
 * which is why it is a local script and never runs in the browser.
 */
import { readFileSync } from 'node:fs'

const markdown = process.argv.includes('--markdown')

function loadEnv() {
  const env = {}
  try {
    for (const line of readFileSync('.env.local', 'utf8').split(/\r?\n/)) {
      if (!line || line.startsWith('#') || !line.includes('=')) continue
      const i = line.indexOf('=')
      env[line.slice(0, i).trim()] = line.slice(i + 1).trim()
    }
  } catch {
    console.error('Could not read .env.local from the repo root.')
    process.exit(1)
  }
  return env
}

const env = loadEnv()
const url = env.NEXT_PUBLIC_SUPABASE_URL
const key = env.SUPABASE_SERVICE_ROLE_KEY
if (!url || !key) {
  console.error('.env.local is missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.')
  process.exit(1)
}

const get = async (path) => {
  const res = await fetch(url + path, {
    headers: { apikey: key, Authorization: `Bearer ${key}` },
  })
  if (!res.ok) throw new Error(`${path} -> ${res.status} ${await res.text()}`)
  return res.json()
}

const [userPage, roleRows, memberRows] = await Promise.all([
  get('/auth/v1/admin/users?per_page=200'),
  get('/rest/v1/user_roles?select=user_id,role'),
  get('/rest/v1/members?select=membership_id,first_name,last_name,primary_email,auth_user_id'),
])

const users = userPage.users ?? []
const rolesByUser = new Map()
for (const r of roleRows) {
  rolesByUser.set(r.user_id, [...(rolesByUser.get(r.user_id) ?? []), r.role])
}
const memberByUser = new Map(
  memberRows.filter((m) => m.auth_user_id).map((m) => [m.auth_user_id, m])
)

// Staff first, then everyone else, each alphabetical.
users.sort((a, b) => {
  const sa = rolesByUser.has(a.id) ? 0 : 1
  const sb = rolesByUser.has(b.id) ? 0 : 1
  return sa - sb || (a.email ?? '').localeCompare(b.email ?? '')
})

const rows = users.map((u) => {
  const m = memberByUser.get(u.id)
  return {
    email: u.email ?? '—',
    roles: (rolesByUser.get(u.id) ?? []).sort().join(', ') || '—',
    member: m ? `${m.membership_id} (${m.first_name ?? ''} ${m.last_name ?? ''})`.trim() : 'not linked',
    lastSignIn: (u.last_sign_in_at ?? 'never').slice(0, 10),
  }
})

const project = url.replace(/^https:\/\//, '').split('.')[0]

if (markdown) {
  console.log(`<!-- generated by scripts/list-access.mjs against ${project} -->`)
  console.log('| Email | Roles | Member record | Last sign-in |')
  console.log('|---|---|---|---|')
  for (const r of rows) console.log(`| \`${r.email}\` | ${r.roles} | ${r.member} | ${r.lastSignIn} |`)
} else {
  console.log(`Supabase project: ${project}\n`)
  const w = (k, min) => Math.max(min, ...rows.map((r) => r[k].length))
  const [we, wr, wm] = [w('email', 5), w('roles', 5), w('member', 13)]
  console.log(`${'EMAIL'.padEnd(we)}  ${'ROLES'.padEnd(wr)}  ${'MEMBER RECORD'.padEnd(wm)}  LAST SIGN-IN`)
  for (const r of rows) {
    console.log(`${r.email.padEnd(we)}  ${r.roles.padEnd(wr)}  ${r.member.padEnd(wm)}  ${r.lastSignIn}`)
  }
}

const staff = rows.filter((r) => r.roles !== '—')
console.log(
  `\n${users.length} auth accounts · ${staff.length} hold a role · ` +
    `${memberByUser.size} of ${memberRows.length} member records linked`
)

// A role with nobody in it cannot be tested, and its routes will look broken.
const held = new Set(roleRows.map((r) => r.role))
const missing = ['Office Staff', 'Office Manager', 'Admin'].filter((r) => !held.has(r))
if (missing.length) console.log(`\nNo account holds: ${missing.join(', ')}`)
